/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    Button: typeof import('./../../components/ui/button/Button.vue')['default']
    Card: typeof import('./../../components/ui/card/Card.vue')['default']
    CardAction: typeof import('./../../components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./../../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../../components/ui/card/CardTitle.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    FormControl: typeof import('./../../components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./../../components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./../../components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./../../components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./../../components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./../../components/ui/input/Input.vue')['default']
    Label: typeof import('./../../components/ui/label/Label.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./../../components/ui/switch/Switch.vue')['default']
    Table: typeof import('./../../components/ui/table/Table.vue')['default']
    TableBody: typeof import('./../../components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./../../components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./../../components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./../../components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./../../components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./../../components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./../../components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./../../components/ui/table/TableRow.vue')['default']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
